# 服务名称
spring:
  application:
    name: catpp-spring-cloud-eureka
  # 安全参数配置
  security:
    user:
      name: root
      password: admin
      roles: SERVICE_NODE
# 服务端口号
server:
  port: 8086

#Eureka 相关配置
eureka:
  client:
    service-url:
      # Eureka默认的服务地址空间信息
      defaultZone: http://localhost:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表（单节点无需配置启用）
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心（单节点无需配置启用）
    register-with-eureka: false
    server:
      waitTimeInMsWhenSyncEmpty: 0