# 服务名称
spring:
  application:
    name: catpp-spring-cloud-eureka-provider
# 服务端口号
server:
  port: 8087

#Eureka 相关配置
#eureka:
#  client:
#    service-url:
#      # Eureka Server 服务注册中心地址
#      defaultZone: http://localhost:8086/eureka/
eureka:
  client:
    service-url:
      # Eureka Server 服务注册中心地址
      defaultZone: http://root:admin@localhost:8086/eureka/
  # 自定义实例编号
  instance:
    # `0.0.1-SNAPSHOT源码的版本号我们是采用了获取pom.xml配置文件内设置的version来设置的值，
    # 通过@xxx@的方式就可以得到maven的一些相关配置信息来直接使用
    instance-id: ${spring.application.name}:${server.port}:0.0.1-SNAPSHOT
    # 配置使用主机方式注册服务
    hostname: node1
    # 配置优先使用IP注册
    prefer-ip-address: true
    # 配置使用指定ip
    ip-address: 127.0.0.1