# 服务名称
spring:
  application:
    name: catpp-spring-cloud-eureka-provider
# 服务端口号
server:
  port: 8087

#Eureka 相关配置
eureka:
  client:
    service-url:
      # Eureka Server 服务注册中心地址
      defaultZone: http://localhost:8081/eureka/
  fetch-registry: false
      # 是否把自己作为服务注册到其他服务注册中心（单节点无需配置启用）
  register-with-eureka: false